version: '3.7'

services:
  postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        env_file:
          - ./backend/.env_local
        ports:
          - "5600:5432"
        
  backend:
    image: python:3.9-alpine
    container_name: backend
    working_dir: /app
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 5800:8000
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    command: sh -c "uvicorn app:app --reload"

  frontend:
    image: node:alpine
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5700:5000"
    command: sh -c "npm install && npm run dev"


