version: '3.7'

services:
  backend:
    image: python:3.9-alpine
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5300:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    command: sh -c "pip install -r requirements.txt && uvicorn app:app --reload"

  frontend:
    image: node:alpine
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5000:5000"
    command: sh -c "npm install && npm run dev"

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - ./backend/.env_local
    ports:
      - "5100:5432"

